# --------- General Configs ---------
GENERAL:
  runner: 'FCoSDRunner'
  task_name: 'LTSF'
  mode: 'train'
  batch_size: 32
  max_epochs: 20
  early_stop_patience: 5


# --------- Data Configs ---------
DATA:
  in_steps: 96
  out_steps: 96
  x_time_of_day: True
  x_day_of_week: True
  y_time_of_day: True
  y_day_of_week: True


# --------- Training Configs ---------  
# TODO: Support more loss functions
OPTIM:
  loss: 'MSE'
  initial_lr: 0.0005
  lr_centers: 0.01
  weight_decay: 0.001
  lr_scheduler_type: 'ExponentialLR'
  lr_scheduler_gamma: 0.8
  clip_grad: 5.0


# --------- Model Configs ---------
# TODO: Add ablation settings.
MODEL_PARAM:
  history_seq_len: 96
  future_seq_len: 96
  num_channels: 134
  d_model: 256
  e_layers: 2
  ffn_activation: 'gelu'
  use_norm: True
  emb_dropout: 0.2
  d_state: 32
  d_conv: 2
  expand: 1
  d_ff: 512
  ffn_dropout: 0.2
  num_bands: 3
  rank: 20
  freq_bands:
    - [0, 0.05]
    - [0.05, 0.1]
    - [0.1, 0.5]
  op_w: 0.01
  input_dim: 256
  spatial_dim: 128
  tod_dim: 64
  dow_dim: 64
  lap_dim: 30
  headdim: 64
  d_inner: 0
  rank2: 32
  node_dim: 64
  d_band: 32
  shared_band: True
  use_adj: True
  use_mamba2: True
  use_mvg: False
  use_rnn: False